"""fix work time in barber

Revision ID: a17aff4aa1ee
Revises: 1e150903b409
Create Date: 2025-08-11 15:52:49.027163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17aff4aa1ee'
down_revision: Union[str, Sequence[str], None] = '1e150903b409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('work_end_time', sa.Time(), nullable=False))
    op.drop_column('barber', 'available_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('available_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('barber', 'work_end_time')
    # ### end Alembic commands ###
